repos:
  # Black — автоформатирование кода
  - repo: https://github.com/psf/black
    rev: 25.11.0
    hooks:
      - id: black
        language_version: python3.12
        args: ["--verbose"]

  # isort — сортировка импортов
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1
    hooks:
      - id: isort
        args: ["--profile", "black", "--verbose"]

  # flake8 — линтинг
  - repo: https://github.com/pycqa/flake8
    rev: 7.3.0
    hooks:
      - id: flake8
        additional_dependencies: ["flake8-pytest-style"]
        args: ["--max-line-length=88", "--show-source", "--statistics"]

  # Хуки от pre-commit
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: end-of-file-fixer

      - id: trailing-whitespace

      - id: check-yaml
      - id: check-added-large-files
